/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.br.produtos;

import com.br.budega.Budega;
import com.br.exception.PNEException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paulo
 */
public class EstocarProdutoPage extends javax.swing.JInternalFrame {

    private Budega budega;
    private String codigo;
    private int indiceEdicao;
    private DefaultTableModel dtmProdutos;
    
    
    public EstocarProdutoPage(Budega budega, String codigo,int indiceEdicao,DefaultTableModel dtmProdutos) {
        this.budega = budega;
        this.codigo = codigo;
        this.indiceEdicao = indiceEdicao;
        this.dtmProdutos = dtmProdutos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtQuantProduto = new javax.swing.JFormattedTextField();
        btnEstoqueProduto = new javax.swing.JButton();

        setClosable(true);
        setTitle("Estocar Produto");
        setToolTipText("");

        jLabel1.setText("Quantidade do Produto para estoque");

        txtQuantProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btnEstoqueProduto.setText("OK");
        btnEstoqueProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(txtQuantProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnEstoqueProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtQuantProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEstoqueProduto)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstoqueProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueProdutoActionPerformed
        int newQuantidade = 0;
        try {
            newQuantidade = budega.consultarProduto(codigo).getQuantidadeProduto() + Integer.parseInt(txtQuantProduto.getText());
            if(newQuantidade < 0){
                newQuantidade = 0;
            }
            
        } catch (PNEException ex) {
            Logger.getLogger(EstocarProdutoPage.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            budega.consultarProduto(codigo).setQuantidadeProduto(newQuantidade);
        } catch (PNEException ex) {
            Logger.getLogger(EstocarProdutoPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        dtmProdutos.setValueAt(Integer.toString(newQuantidade), indiceEdicao,3);
        
        
        this.dispose(); //fecha a janela
    }//GEN-LAST:event_btnEstoqueProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstoqueProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField txtQuantProduto;
    // End of variables declaration//GEN-END:variables
}
