/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.br.produtos;

import com.br.budega.Budega;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paulo
 */
public class VenderProduto extends javax.swing.JInternalFrame {
    
    private Budega budega;
    private String codigo;
    private int indiceEdicao;
    private DefaultTableModel dtmProdutos;
   
    public VenderProduto(Budega budega, String codigo,int indiceEdicao,DefaultTableModel dtmProdutos) {
        this.budega = budega;
        this.codigo = codigo;
        this.indiceEdicao = indiceEdicao;
        this.dtmProdutos = dtmProdutos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtQuantProduto = new javax.swing.JFormattedTextField();
        btnVendaProduto = new javax.swing.JButton();

        setClosable(true);
        setTitle("Venda de Produto");

        jLabel1.setText("Quanrtidade do Produto para venda");

        txtQuantProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btnVendaProduto.setText("OK");
        btnVendaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(txtQuantProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnVendaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtQuantProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVendaProduto)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVendaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaProdutoActionPerformed
        
        int newQuantidade = budega.consultarProduto(codigo).getQuantidadeProduto() - Integer.parseInt(txtQuantProduto.getText());

        budega.consultarProduto(codigo).setQuantidadeProduto(newQuantidade);
        dtmProdutos.setValueAt(Integer.toString(newQuantidade), indiceEdicao,3);
        
        
        this.dispose(); //fecha a janela
    }//GEN-LAST:event_btnVendaProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVendaProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField txtQuantProduto;
    // End of variables declaration//GEN-END:variables
}
